service: yuuka

useDotenv: true

plugins:
  - serverless-scriptable-plugin

provider:
  name: aws
  runtime: nodejs20.x

  region: ap-northeast-1
  stage: dev

  memorySize: 512
  architecture: arm64

  logRetentionInDays: 5
  versionFunctions: false
  timeout: 5

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"

    AWS_ACCOUNT_ID: ${aws:accountId}

    STAGE: ${self:provider.stage}
    NODE_ENV: production

    SUPABASE_PROJECT_REF: ${env:SUPABASE_PROJECT_REF}
    SUPABASE_SERVICE_KEY: ${env:SUPABASE_SERVICE_KEY}

package:
  individually: true
  patterns:
    - "!**"
    - "!node_modules/**"

functions:
  httpMain:
    handler: artifact/http_main.dispatch
    url: true
    package:
      patterns:
        - artifact/http_main.mjs*
        - static/**/*
        - views/**/*
        - priv/**/*
    events:
      - httpApi:
          method: ANY
          path: /
      - httpApi:
          method: ANY
          path: /{pathname+}

custom:
  scriptHooks:
    before:package:createDeploymentArtifacts: pnpm artifact
