version: "3"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: localhost_dev
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: localhost

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
