service: yuuka

frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-git-info
  - serverless-scriptable-plugin

provider:
  name: aws
  runtime: nodejs20.x

  region: ap-northeast-1
  stage: ${opt:stage, 'main'}

  memorySize: 512
  architecture: arm64

  logRetentionInDays: 7
  versionFunctions: false
  timeout: 5

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"

    AWS_ACCOUNT_ID: ${aws:accountId}
    STAGE: ${self:provider.stage}

    DATABASE_URL: ${env:DATABASE_URL}

    GIT_COMMIT: ${git:commit}
    GIT_BRANCH: ${git:branch}

package:
  individually: true
  patterns:
    - "!**"
    - "!node_modules/**"

functions:
  httpHandler:
    handler: artifact/http_handler.dispatch
    package:
      patterns:
        - artifact/http_handler.mjs*
        - priv/**/*
        - static/**/*
    events:
      - httpApi: ANY /healthcheck/{pathname+}
      - httpApi: ANY /api/{pathname+}

custom:
  scriptHooks:
    before:package:createDeploymentArtifacts: pnpm artifact
